obj-y					+= tee_stub.o
obj-$(CONFIG_TRIX_MCU_COMM)		+= mcuctrl.o
obj-$(CONFIG_TRIX_SECURE_FIRMWARE)	+= secure_firmware.o
obj-$(CONFIG_TRIX_TEE_OPTEE)		+= tee_sip.o
obj-$(CONFIG_TRIX_TEE_ARMOR)		+= tee_armor.o
