obj-$(CONFIG_GMAC_ETH) += dwmac.o
dwmac-objs := dwmac_main.o dwmac_ethtool.o dwmac_mdio.o ring_mode.o \
	      chain_mode.o dwmac_lib.o dwmac1000_core.o dwmac1000_dma.o \
	      enh_desc.o norm_desc.o mmc_core.o dwmac-trix.o
