#
# Sigmadesigns DTV drivers
#
obj-$(CONFIG_TRIX_SOC_INFO)	+= soc-info.o
obj-$(CONFIG_SYSCON_TRIX)	+= syscon.o
obj-$(CONFIG_TRIX_HIDTVMEM)	+= hidtvmem.o
obj-$(CONFIG_TRIX_DRV_HELPER)	+= helper/
obj-$(CONFIG_TRIX_OTP_FUSE)	+= otp/
obj-y				+= firmware/
obj-y				+= sd_mem_pool.o
