#ifndef __TRIX_ASM_OFFSETS_H__
#define __TRIX_ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by Kbuild
 */

#define S2RAM_ENTRY_OFS 0 /* offsetof(struct s2ram_resume_frame, S2RAM_ENTRY)	@ */

#define MCTL_OFS_IF_ENABLE 0 /* offsetof(struct umac_mac, mctl.if_enable)	@ */

#define PCTL_OFS_CFG1 4 /* offsetof(struct umac_phy, pctl.cfg1)	@ */
#define PCTL_OFS_CFG4 16 /* offsetof(struct umac_phy, pctl.cfg4)	@ */
#define PCTL_OFS_PHY_PAD_CTL 1312 /* offsetof(struct umac_phy, pctl.phy_pad_ctl)	@ */
#define PCTL_OFS_UNIQUIFY_IO_1 1392 /* offsetof(struct umac_phy, pctl.uniquify_io_1)	@ */
#define PCTL_OFS_SCL_START_ADDR 1416 /* offsetof(struct umac_phy, pctl.phy_scl_start_addr)	@ */
#define PCTL_OFS_DDR4_CONFIG_1 1476 /* offsetof(struct umac_phy, pctl.ddr4_config_1)	@ */
#define PCTL_OFS_VREF_TARINING 1480 /* offsetof(struct umac_phy, pctl.vref_training)	@ */
#define PCTL_OFS_REG4 4016 /* offsetof(struct umac_phy, pctl.reg4)	@ */

#define SIZEOF_UMAC_DEV 24 /* sizeof(struct umac_device)	@ */
#define UDEV_OFS_MAC 0 /* offsetof(struct umac_device, mac)	@ */
#define UDEV_OFS_PHY 4 /* offsetof(struct umac_device, phy)	@ */
#define UDEV_OFS_ABT 8 /* offsetof(struct umac_device, abt)	@ */
#define UDEV_OFS_WIDTH 12 /* offsetof(struct umac_device, width)	@ */
#define UDEV_OFS_QUIRKS 16 /* offsetof(struct umac_device, quirks)	@ */
#define UDEV_OFS_ADDR 20 /* offsetof(struct umac_device, addr)	@ */


#endif
